"""
```sidif
# 🌐🕸
test_extractor isA PythonModule
  "Wolfgang Fahl" is author of it
  "2025-11-29" is createdAt of it
  "Test main micro annotation snippet extraction" is purpose of it
```
"""

from tests.base_sem3test import BaseSem3test


class Test_Extractor(BaseSem3test):
    """Test the extractor."""

    def setUp(self, debug=True, profile=True):
        BaseSem3test.setUp(self, debug=debug, profile=profile)

    def test_extract_from_own_source(self):
        """Test that the extractor can find annotations in the project's own
        source code."""
        markups = self.get_markups()
        self.assertGreaterEqual(len(markups), 3)
        for markup in markups:
            self.assertTrue("isA" in markup.code)
            if "isA PythonModule" in markup.code:
                for field in ["author", "createdAt", "purpose"]:
                    self.assertTrue(field in markup.code, field)

    def test_issue_5(self):
        """
        test the apache configuration example
        """
        # Apache Configuration for ypgen.bitplan.com
        # py-yprinciple-gen Version 0.3.0 of 2024-03-30 (python Y-Principle generator)
        # Generated by WebserverCmd at 2024-07-23T09:19:32.709025
        # http Port: 8778
        # SSL Port: 443
        #
        # timeout: 3.0
        # ```yaml
        # 🌐🕸 Embedded Yaml snippet for index.html generator
        # ypgen.bitplan.com:
        #   isA: Service
        #   ui: nicegui
        #   url: https://ypgen.bitplan.com
        #   createdAt: 2024-07-23T09:19:32.709025
        #   publicity: intranet
        # ```
        # We scan the current file "test", "test_extractor.py"
        # which has an embedded markup above
        markups = self.get_markups("tests", "test_extractor.py")

        found = False
        for markup in markups:
            # We look for the snippet defined in the docstring above
            if "ypgen.bitplan.com" in markup.code:
                found = True

                # Assertions to prove the prefix stripping worked:
                # 1. The code should not contain the "# " prefix
                self.assertFalse(
                    markup.code.lstrip().startswith("#"), "Prefix '# ' was not stripped"
                )

                # 2. Content verification
                self.assertIn("isA: Service", markup.code)
                self.assertIn("ui: nicegui", markup.code)
                self.assertIn("publicity: intranet", markup.code)

                # 3. Lang verification
                self.assertEqual("yaml", markup.lang)

        self.assertTrue(
            found, "The embedded YAML block in the docstring was not extracted."
        )
